### ISSUE TITLE
scheduled for 5 days

### ISSUE THREAD

**Issue by sodabarauf** [sodabarauf/space-travelers-hub#1]
in these 6 days all requirements of project will done.

**Comment by ahzamir** [comment]
@sodabarauf 
@elhamy786 
@Breshnahamidi20 

Well done team, just add some tasks for every component design for example the task for the missions page mobile design and desktop design using tailwind or Bootstrap

Please have a look on my comments on some of the tasks, your kanban board has been approved and you can start work on your project Good luck
