### ISSUE TITLE
profile part (group task) [6H]

### ISSUE THREAD

**Issue by sodabarauf** [sodabarauf/space-travelers-hub#8]
description: creation of profile.js file in pages folder and profileActions.js file in redux/actions/reducers.
-sodaba
-elham
-breshna

**Comment by ahzamir** [comment]
- This age includes the data from all of your components like from the missions component the joined mission data, the Rockets component the rockets that have been reserved, and ...

- So I mean this task should be done after you finish other pages and components and this should be done as a group so change this to a group task and assign them to all team members
